### ISSUE TITLE
Installations fails on dependency get-cursor-position fork

### ISSUE THREAD

**Issue by EdJoPaTo** [slammayjammay/node-pager#2]
I tested to install this on Linux and macOS with the same result. 

Installing the dependency [patrickkettner/get-cursor-position](https://github.com/patrickkettner/get-cursor-position) seems not to work. I wondered why using this fork and tried to install [bubkoo/get-cursor-position](https://github.com/bubkoo/get-cursor-position) without any problems. I don't see why the fork is used here looking at the [compare](https://github.com/bubkoo/get-cursor-position/compare/master...patrickkettner:master). Do I miss something?

```
> $ node -v                                                                                                  
v11.11.0
                                                                                                              
> $ npm -v                                                                                                   
6.9.0
```

```
> $ npm i node-pager                                                                                         

> @patrickkettner/get-cursor-position@1.0.4 install /home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for @patrickkettner/get-cursor-position@1.0.4 and node@11.11.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for @patrickkettner/get-cursor-position@1.0.4 and node@11.11.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build'
  CXX(target) Release/obj.target/pos/src/pos.o
make: Entering directory '/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build'
  CXX(target) Release/obj.target/pos/src/pos.o
../src/pos.cc: In function ‘void Method(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/pos.cc:259:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, row, col;
      ^~~
In file included from ../src/pos.cc:1:
../src/pos.cc: At global scope:
/home/edjopato/.node-gyp/11.11.0/include/node/node.h:495:43: warning: cast between incompatible function types from ‘void (*)(v8::Handle<v8::Object>)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_fun’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/edjopato/.node-gyp/11.11.0/include/node/node.h:529:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/pos.cc:283:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(hello, Init)
 ^~~~~~~~~~~
../src/pos.cc: In function ‘void Method(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/pos.cc:259:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, row, col;
      ^~~
In file included from ../src/pos.cc:1:
../src/pos.cc: At global scope:
/home/edjopato/.node-gyp/11.11.0/include/node/node.h:495:43: warning: cast between incompatible function types from ‘void (*)(v8::Handle<v8::Object>)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_fun’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/edjopato/.node-gyp/11.11.0/include/node/node.h:529:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/pos.cc:283:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(hello, Init)
 ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/pos.node
sed: can't read ./Release/.deps/Release/obj.target/pos/src/pos.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/pos/src/pos.o.d.raw': No such file or directory
make: *** [pos.target.mk:99: Release/obj.target/pos/src/pos.o] Error 1
make: Leaving directory '/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 5.0.2-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node" "--module_name=pos" "--module_path=/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build/Release"
gyp ERR! cwd /home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position
gyp ERR! node -v v11.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node --module_name=pos --module_path=/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/edjopato/Documents/tmp/nodejs-test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:984:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 5.0.2-arch1-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/edjopato/Documents/tmp/nodejs-test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position
node-pre-gyp ERR! node -v v11.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node --module_name=pos --module_path=/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build/Release' (1)
  COPY Release/pos.node
make: Leaving directory '/home/edjopato/Documents/tmp/nodejs-test/node_modules/@patrickkettner/get-cursor-position/build'
npm WARN nodejs-test@1.0.0 No description
npm WARN nodejs-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @patrickkettner/get-cursor-position@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @patrickkettner/get-cursor-position@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edjopato/.npm/_logs/2019-03-17T10_41_37_593Z-debug.log
```

**Comment by slammayjammay** [comment]
Thanks for opening this. Don't know why this error is thrown on new versions of node but that dependency is removed in v0.3.3 (694d483).
